### ISSUE TITLE
Is there a list of labrad types?

### ISSUE THREAD

**Issue by joshmutus** [labrad/pylabrad-wiki#1]
In trying to follow [how to write a server](https://github.com/labrad/pylabrad-wiki/blob/master/Writing-Servers.md) the type of the input and return are specified in the ```@setting``` decorator. Is there a list of what these types mean somewhere?  I can guess at some of them, but it would be helpful.

**Comment by DanielSank** [comment]
https://github.com/labrad/pylabrad-wiki/blob/master/python----wire-type-conversion-rules.md

**Comment by DanielSank** [comment]
Please remember that this wiki repo is an experiment. The official documentation is still the wiki attached to the pylabrad repo.

**Comment by joshmutus** [comment]
Added a link to this in the servers page, made a pull request for that change.

Thanks!
